spring.application.name=security
spring.config.import=optional:file:.env.properties
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate'i sadece do?rulamaya çekiyoruz, tablolar? Flyway yönetecek
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway'i aktif ediyoruz
spring.flyway.enabled=true
# E?er ?ema ismin farkl?ysa belirtebilirsin (genelde public'tir)
spring.flyway.schemas=public